name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: archie0223
          password: 668866wmywanm

      - name: Generate timestamp tag
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag app-archie:${{ env.TAG }}

      - name: Tag the image for Docker Hub
        run: docker tag app-archie:${{ env.TAG }} archie0223/app-archie:${{ env.TAG }}

      - name: Push the image to Docker Hub
        run: docker push archie0223/app-archie:${{ env.TAG }}

