name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t archie0223/app-archie:1745379068 .

      - name: Save Docker image as tar
        run: docker save archie0223/app-archie:1745379068 -o app-archie.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: app-archie.tar

  push:
    runs-on: ubuntu-latest
    needs: build  # ensures this runs after the build job
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: app-image
          path: .

      - name: Load Docker image
        run: docker load -i app-archie.tar

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push archie0223/app-archie:1745379068
